config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/search", to: 'requests#index'
  get "/search_sweets", to: 'sweets#index'

  resources :requests, only: [:index, :show, :create, :destroy] do
    resources :offers, only: [:new, :create, :show, :edit, :update]
  end
  resources :offers, only: [] do
    resources :messages, only: [:create]
  end

  resources :sweets, only: [:index, :show] do
    resources :requests, only: [:new]
  end

  resources :statusoffer, only: [:edit]

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  get 'profile', to: 'pages#profile', as: 'profile'


  mount ActionCable.server => "/cable"

end

app/views/pages/shared/_offer_tab.html.erb
<div class="cards-wr-margin">
  <h2 id="blue">OFFERS RECENTLY MADE</h2>
  <div class="flex-card-container">
    <% @offers_pend.each do |offer| %>
      <div class="card-offer-content">
        <p class="candy-pic"> <%= image_tag "#{offer.request.sweet.picture}"%> </p>
        <div class="card-offer-text">
          <h3> <%= offer.request.sweet.name %> </h3>
          <p> Status: <%= offer.status %> </p>
          <p> <i class="far fa-calendar-alt"></i> <%= offer.end_date %> </p>
          <p> <i class="fas fa-map-marked-alt"></i> <%= offer.user.city %> </p>
          <p> <%= link_to "Request", request_path(offer.request) %> </p>
          <p> <%= link_to 'Offer', request_offer_path(request_id: offer.request_id, id: offer.id) %></p>
        </div>
      </div>
    <% end %>
  </div>

  <h2 id= "blue"> ARCHIVED OFFERS</h2>
  <div class="flex-card-container">
    <% @offers_arch.each do |offer| %>
      <div class="card-offer-content">
        <p class="candy-pic"> <%= image_tag "#{offer.request.sweet.picture}"%> </p>
        <div class="card-offer-text">
          <h3> <%= offer.request.sweet.name %> </h3>
          <p> Status: <%= offer.status %> </p>
          <p> <i class="far fa-calendar-alt"></i> <%= offer.end_date %> </p>
          <p> <i class="fas fa-map-marked-alt"></i> <%= offer.pick_up_location %> </p>
          <p> <%= link_to "Details", request_path(offer.request) %> </p>
        </div>
      </div>
    <% end %>
  </div>

  <h2 id="blue"> CANCELED OFFERS</h2>
  <div class="flex-card-container">
    <% @offers_canc.each do |offer| %>
      <div class="card-offer-content">
        <p class="candy-pic"> <%= image_tag "#{offer.request.sweet.picture}"%> </p>
        <div class="card-offer-text">
          <h3> <%= offer.request.sweet.name %> </h3>
          <p> Status: <%= offer.status %> </p>
          <p> <i class="far fa-calendar-alt"></i> <%= offer.end_date %> </p>
          <p> <i class="fas fa-map-marked-alt"></i> <%= offer.pick_up_location %> </p>
          <p> <%= link_to "Details", request_path(offer.request) %> </p>
        </div>
      </div>
    <% end %>
  </div>


</div>

app/views/pages/shared/_request_tab.html.erb
<div class="cards-wr-margin">
  <h2> ALL YOUR REQUESTS</h2>
    <% @requests.each do |request| %>
      <div class="card-request-content container mb-5">
        <div class="row">
          <div class="card-request-info col-4">
            <p class="candy-pic-request"> <%= image_tag "#{request.sweet.picture}"%> </p>


            <div class="card-request-text">
              <h3> <%= request.sweet.name %> </h3>
              <p> <%= request.quantity %> x <i class="fas fa-candy-cane"></i></p>
              <p> <i class="fas fa-globe-americas"></i> <%= request.sweet.country %> </p>
              <p> <i class="fas fa-heart"></i> <%= request.charity.name %> </p>

              <div class="calculator rc-16">
                <div class="d-flex justify-content-between">
                  <span> Candy </span>
                  <span><%= convert_currency(request.price_cents) %> €</span>
                </div>
                <div class="card-border-bottom-show d-flex justify-content-between">
                  <p> Charity </p><p><%= convert_currency(request.donation_cents) %> €</p>
                </div>
                <div class="d-flex justify-content-between">
                  <p>total </p><p><%= convert_currency(request.price_cents + request.donation_cents) %></p>
                </div>
              </div>

            </div>
          </div>
          <!-- <div class="col-1"></div> -->
          <div class="card-offer-list col-8">

            <% if request.offers.count == 0 %>
              <p id="oupsy">Oupsy! No offers yet!</p>
              <% else %>
              <p> Damn it! Here are the offers for your Candy request:</p>
            <% end %>

            <% request.offers_to_display.each do |offer| %>

              <% if offer.status == 'decline' %>
                <div class="card-offer-declined rc-16 my-3" id="id_<%= offer.id %>">
              <% else %>
                <div class="card-offer-details rc-16 my-3">
              <% end %>

                <div class="d-flex flex-nowrap justify-content-around align-items-center">

                  <div class="mx-1">
                    <p>
                    <%= image_tag "#{offer.user.photo}", class: "avatar", id: "avatar-chat" %>
                    <%= offer.user.full_name %>
                    </p>
                  </div>

                  <div class="mx-1 flex-fill">
                    <p><%= offer.content %></p>
                  </div>

                  <div class="mx-1 ">
                    <%= link_to 'Chat', request_offer_path(request_id: offer.request_id, id: offer.id), class: 'mini-detail-button'   %>

                  </div>


                  <% if offer.confirmed? %>
                    <div class="mx-1"></div>
                    <%= form_tag orders_path do %>
                      <%= hidden_field_tag 'request_id', request.id %>
                      <%= submit_tag 'BUY', class: 'buy-button blink_button' %>
                    <% end %>

                    </div>


                  <% else %>

                    <div class=" d-flex flex-column">
                      <%= link_to 'confirm', edit_statusoffer_path(id: offer.id, status: 0), class: 'mini-button ml-4 mb-2 confirm-button'  %>
                      <%= link_to 'decline', edit_statusoffer_path(id: offer.id, status: 2), class: 'mini-button ml-4 mb-2'  %>
                    </div>
                  <% end %>

              </div>
            </div>
                <% end %>

          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/pages/shared/_user_info.html.erb
<div class="profile-info rc-16 mt-3 ml-5">
  <%= image_tag "#{@user.photo}", alt: "Avatar", width: 200 %>
  <div class="sections">
    <h5>SWEET-HERO</h5>
    <h5>CANDIES</h5>
  </div>

  <h3 class="icons-user"> <%= @user.full_name %> </h3>
  <p> <i class="fas fa-candy-cane"></i> <%= @sum_requests %> Requests made </p>
  <p> <i class="fas fa-luggage-cart"></i> <%= @sum_confirmed_offers %> times a Hero </p>
  <p> <i class="fas fa-hand-holding-heart"></i> <%= @sum_donation %> € Raised </p>
</div>