config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/search", to: 'requests#index'
  get "/search_sweets", to: 'sweets#index'

  resources :requests, only: [:index, :show, :create, :destroy] do
    resources :offers, only: [:new, :create, :show, :edit, :update]
  end
  resources :offers, only: [] do
    resources :messages, only: [:create]
  end

  resources :sweets, only: [:index, :show] do
    resources :requests, only: [:new]
  end

  resources :statusoffer, only: [:edit]

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  get 'profile', to: 'pages#profile', as: 'profile'


  mount ActionCable.server => "/cable"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% if user_signed_in? %>
    <%= link_to "CANDY REQUEST", requests_path, class: "nav-link" %>
    <%= link_to "CANDIES", sweets_path,  class: "nav-link" %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-inline.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "PROFILE", profile_path, class: "nav-link" %>
    <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "nav-link" %>
  <% else %>
    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  <% end %>
  </div>
</div>