config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/search", to: 'requests#index'
  get "/search_sweets", to: 'sweets#index'

  resources :requests, only: [:index, :show, :create, :destroy] do
    resources :offers, only: [:new, :create, :show, :edit, :update]
  end
  resources :offers, only: [] do
    resources :messages, only: [:create]
  end

  resources :sweets, only: [:index, :show] do
    resources :requests, only: [:new]
  end

  resources :statusoffer, only: [:edit]

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  get 'profile', to: 'pages#profile', as: 'profile'


  mount ActionCable.server => "/cable"

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :charity
  belongs_to :sweet
  belongs_to :user
  has_many :offers

  include PgSearch::Model
  pg_search_scope :search_sweet_name_and_country,
                  against: [],
                  associated_against: {
                    sweet: [:name, :country]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  pg_search_scope :search_request_per_city,
                  against: [],
                  associated_against: {
                    user: [:city]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  DONATION = [5, 10, 15, 20]

  # monetize :price_cents
  # monetize :donation_cents

  def confirmed_offers
    offers.where(status: :confirmed)
  end

  def offers_to_display
    return confirmed_offers if confirmed_offers.present?
    return offers.sort
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :find_request, only: [:show, :destroy]
  include MoneyConverterHelper
  def index
    @requests = Request.all
    @requests = @requests.search_sweet_name_and_country(params[:search_sweet_name_and_country]) if params[:search_sweet_name_and_country].present?
    @requests = @requests.search_request_per_city(params[:search_user_city]) if params[:search_user_city].present?

    @markers = geocode_request(@requests)
  end

  def show
    @request = Request.find(params[:id])
    @offers  = Offer.where(request_id: @request.id)
    @sum_requests = sum_requests
    @number_time_hero = number_time_hero
    @money_raised = money_raised
  end

  def new
    @request = Request.new()
    @request.sweet_id = params[:sweet_id]
    @charities = Charity.all
    @candies = Sweet.all
  end

  def create
    @request = Request.new(request_params)
    @request.user = current_user
    if @request.save
      @request.donation_cents = cent_to_euro(request_params["donation_cents"])
      @request.price_cents = cent_to_euro(request_params["price_cents"])
      @request.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

  def destroy
    offers = Offer.where(request_id: @request.id)
    offers.each do |offer|
      offer.destroy
    end
    @request.destroy
    redirect_to root_path
  end

  private

  def find_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:description, :price_cents, :donation_cents, :quantity, :charity_id, :sweet_id)
  end

  def geocode_request(requests)
    requests.map do |request|
      {
        lat: request.sweet.latitude,
        lng: request.sweet.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { request: request }),
        image_url: helpers.asset_url('http://www.dacoromania.org/upload/o/2/20213_candy-png.png')
      }
    end
  end

  def sum_requests
    @request.user.requests.count
  end

  def number_time_hero
    @request.user.offers.where(status: :confirmed).count
  end

  def money_raised
    money = 0
    @request.user.offers.where(status: :confirmed).each do |offer|
      money += offer.request.donation_cents
    end
    convert_currency(money)
  end
end

app/views/requests/_info_window.html.erb
<div class="container card-map rounded">
  <div class="row justify-content-center">
    <p> <%= cl_image_tag(request.sweet.picture,
          {id: "img-sweet-map"}) %> </p>
  </div>
  <div class="text-center">
    <h3> <%= request.sweet.name %></h3>
    <p>From <%= request.sweet.country %></p>
  </div>
  <div class="row align-items-center">
    <div class="col-sm">
      <p> <%= cl_image_tag(request.user.photo,
            {class: "avatar-large"}) %> </p>
    </div>
    <div class="col-sm">
      <p> <%= request.user.full_name %></p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="btn-action mt-2 col-10">
      <%= link_to "LET'S GO!", request_path(request) %>
    </div>
  </div>
</div>

app/views/requests/_offer.html.erb
<% @offers.each do |offer| %>
  <%= link_to request_offer_path(offer.id), :action => 'go', class: "card card-light" do %>
    <div class="">
      <%= cl_image_tag(offer.user.photo,
      {class: "avatar"}) %>
    </div>
    <%= offer.content %>
    <%= offer.created_at.to_formatted_s(:long_ordinal)  %>
  <% end %>
<% end %>

app/views/requests/_request_details.html.erb
<div class="row mb-3" id='img-sweet'>
  <div class="col-sm">
    <h2 class="header-thick"><%= @request.sweet.name %></h2>
    <div class="small-text-align">
      <p class="text-details"> created on <%= @request.created_at.to_formatted_s(:long_ordinal) %></p>
      <p> <i class="fas fa-map-marked-alt"></i> &nbsp; <%= @request.user.city %></p>
      <p> <i class="fas fa-plane-departure"></i>  &nbsp; <%= @request.sweet.country %></p>
      <p> <%= @request.quantity %> X &nbsp;<i class="fas fa-candy-cane"></i></p>
      <p style="line-height: 1.5;"> <i class="far fa-envelope"></i> &nbsp;<%= @request.description %></p>
    </div>
  </div>

  <div class="col-sm d-flex align-items-center justify-content-center">
    <%= cl_image_tag(@request.sweet.picture,
    crop: :fill) %>
  </div>
</div>

<div class="row align-items-end">
  <div class="col-6">
    <% if @request.user != current_user %>
      <div class="btn-action" id= "offer">
        <%= link_to 'MAKE AN OFFER', new_request_offer_path(@request) %>
      </div>
    <% else %>
      <div class="btn-action" id= "offer">
        <%= link_to 'GO TO PROFILE', profile_path %>
      </div>
    <% end %>
  </div>

  <div class="col-1"></div>

  <div class="col-4">
    <div class="card-addition-request">
      <p><i class="fas fa-heart"></i> <%= @request.charity.name %></p>
      <p> Donation: <%= convert_currency(@request.donation_cents) %> </p>
      <div class="card-border-bottom-show">
        <p> Estimate price: <%= convert_currency(@request.price_cents)%></p>
      </div>
      <p> Estimate total: <%= convert_currency(@request.price_cents + @request.donation_cents)%></p>
    </div>
  </div>

  <div class="col-1"></div>

</div>

app/views/requests/_request_index.html.erb
<% @requests.each do |request| %>
  <%= link_to request_path(request.id), :action => 'go', class: "card card-request" do %>
    <%= cl_image_tag(request.sweet.picture,
    {class:"card-picture rc-16"}) %>

    <div class="card-request-info">
      <div>
        <h5> <%= request.sweet.country %></h5>
        <div class="card-charity">
          <p style="font-size: 14px;"> <i class="fas fa-heart"></i> <%= request.charity.name %></p>
      </div>
        </div>
        <div class="card-avatar">
          <%= cl_image_tag(request.user.photo,
           {class: "avatar"}) %>
           <p>  <%= request.user.full_name %> from <%= request.user.city %></p>
        </div>
    </div>
  <% end %>
<% end %>

app/views/requests/create.html.erb
<h1>Requests#create</h1>
<p>Find me in app/views/requests/create.html.erb</p>

app/views/requests/delete.html.erb
<h1>Requests#delete</h1>
<p>Find me in app/views/requests/delete.html.erb</p>

app/views/requests/index.html.erb
<div class="container-top sticky-search-reguest">
  <div class="left-lighting">
  <%= image_tag 'https://static.wixstatic.com/media/d57200_7b185c116c4a49138fdeeaf8e1b7d28f~mv2.gif', id: "left-lighting" %>
</div>

<div class="inner-sticky">
  <h1>Become a hero, fix a sweet junkie!</h1>


  <div class="align-search-bar">

    <%= form_tag(search_path, method: "get", class: "search_bar") do %>

      <%= text_field_tag :search_user_city, nil, placeholder: "Where are you?" %>
      <%= text_field_tag :search_sweet_name_and_country, nil, placeholder: "Where you wanna go?" %>
      <i id='search_icon' class="fa fa-search searchIcon"></i>
      <%= submit_tag "", id:'search_button'%>
    <% end %>

  </div>
</div>
  <div class="right-lighting">
  <%= image_tag 'https://static.wixstatic.com/media/d57200_7b185c116c4a49138fdeeaf8e1b7d28f~mv2.gif', id: "right-lighting" %>
</div>
</div>

<div class="main-container background">
  <div class="requests-container">
    <%= render 'request_index' %>
  </div>

  <div class="container-map">
    <div
      id="map"
      style="width: 480px;
      height: 480px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div>
</div>

app/views/requests/new.html.erb
<div class="request-form-container my-5">
    <div class="text-center">
      <h1>Request for <%= @request.sweet.name %> </h1>
    </div>
  <%= simple_form_for(@request) do |f| %>
    <div class="row">
      <div class="col-md-8 ">
        <div class="row">
          <div class="col-md-12">
            <%= f.error_notification %>
            <%= f.input :description, label: 'Write a Message to your hero:', input_html: { class: 'round-form' } %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-6">
                <%= f.input :price_cents, label: 'Candy price:', input_html: { class: 'round-form' }%>
              </div>
              <div class="col-md-6">
                <%= f.input :quantity, label: 'Number of pack:', input_html: { class: 'round-form' }%>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <legend class="col-form-label pt-0">Donation</legend>
            <div class="form-check pl-0">
              <% Request::DONATION.each do |d| %>
                <input class="no-display round-form" type="radio" value="<%= d %>" name="request[donation_cents]" id="request_donation_cents_<%= d %>" />
                <label class="collection_check_boxes form-label-donation round-form" for="request_donation_cents_<%= d %>"> <%= d %>
                </label>
              <% end %>
            </div>

          </div>
        </div>
      </div>
      <div class="col-md-4 text-center d-flex justify-content-between flex-column">
        <div class="row">
          <div class="col-md-12">
          <%= cl_image_tag(@request.sweet.picture, {id: 'sweet-image-container'}) %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="row mb-3">
          <div class="col-md-12">
            <legend class="col-form-label pt-0">Pick a Charity</legend>
          </div>
        </div>
        <div class="row ml-5">
          <div class="col-sm-12">
            <div class="d-flex flex-wrap justify-content-around">
              <% Charity.all.each do |charity| %>
                <div class="img-charity align-self-center mr-5">
                  <input class="no-display" type="radio" value="<%= charity.id %>" name="request[charity_id]" id="request_charity_id_<%= charity.id %>">
                  <label class="form-charity-label radio_buttons required fit-img rc-16" for="request_charity_id_<%= charity.id %>"> <%= cl_image_tag(charity.picture, {class: "rc-16"})%> </label>
                </div>
              <% end %>
            </div>
          </div>

        </div>
        <input type="hidden" value="<%= @request.sweet_id %>" name="request[sweet_id]" id="request_sweet_id">
      </div>
    </div>
    <div class="row mt-4">
      <div class="col-3"></div>
          <div class="form-group col-md-6">
            <div class=“form-actions”>
              <%= f.button :submit, class: 'btn-action w-100' %>
            </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/requests/show.html.erb
<div class="background">
  <div class="container-show-request row justify-content-between">
    <div class="card-request-sidebar col-3">
        <%= link_to "Back to candies", sweets_path, class: "btn-return"%>
      <div class="card-request-user py-5 px-4 mb-5">
          <%= cl_image_tag(@request.user.photo,
          {class: "avatar-xl"}) %>
        <div class="card-pink-p mt-3">
          <p>Sweetie</p>
        </div>
          <p>  <%= @request.user.full_name %></p>
        <div class="text-left">
          <p> <%= image_tag "lolly.png", class: "icon-xs" %> &nbsp; <%= @sum_requests %> requests made </p>
          <p> <%= image_tag "suitcase.png", class: "icon-xs" %> &nbsp;<%= @number_time_hero %> times a hero </p>
          <p> <%= image_tag "heart.png", class: "icon-xs" %> &nbsp; <%= @money_raised %>€ raised</p>
        </div>
      </div>
    </div>

    <div class="card-request-show container col-8">
      <%= render 'request_details' %>
    </div>
  </div>
</div>