config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/search", to: 'requests#index'
  get "/search_sweets", to: 'sweets#index'

  resources :requests, only: [:index, :show, :create, :destroy] do
    resources :offers, only: [:new, :create, :show, :edit, :update]
  end
  resources :offers, only: [] do
    resources :messages, only: [:create]
  end

  resources :sweets, only: [:index, :show] do
    resources :requests, only: [:new]
  end

  resources :statusoffer, only: [:edit]

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  get 'profile', to: 'pages#profile', as: 'profile'


  mount ActionCable.server => "/cable"

end

app/models/sweet.rb
class Sweet < ApplicationRecord
  has_many :requests
  geocoded_by :country
  after_validation :geocode, if: :will_save_change_to_country?

  include PgSearch::Model
  pg_search_scope :search_sweet,
                  against: [ :name, :country, :category, :description ],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController

  def index
    if params[:query] == ''
      @sweets = Sweet.all
    elsif params[:query]
      @sweets = Sweet.search_sweet(params[:query])
    else
      @sweets = Sweet.all
    end
  end

  def show
    @sweet = Sweet.find(params[:id])
  end
end

app/views/sweets/index.html.erb
<div class="container-top sticky-search-reguest">
  <div>
    <%= image_tag 'https://media.giphy.com/media/QBwTvLxN5kHvIsvw3B/giphy.gif', id: "left-candy" %>
  </div>
  <div>
    <h1>Candy? Fix dat craving!</h1>

    <%= form_tag(search_sweets_path, method: "get", class: "search_bar") do %>

      <%= text_field_tag :query, nil, placeholder: "Search by sweet name, country and category" %>
      <i id='search_icon' class="fa fa-search searchIcon"></i>
      <%= submit_tag "", id:'search_button'%>
    <% end %>
  </div>
  <div>
    <%= image_tag 'https://media.giphy.com/media/QBwTvLxN5kHvIsvw3B/giphy.gif', id: "right-candy" %>
  </div>
</div>

<div class="container-sweet">
  <% @sweets.each do |sweet| %>
  <div class="card-sweet">
    <div class="card-img">
      <%= link_to cl_image_tag(sweet.picture, {class:"rc-16"}), new_sweet_request_path(sweet.id) %>
    </div>
      <div class="card-info">
        <h6><%= sweet.country %></h6>
        <p><%= sweet.description %></p>
      </div>
  </div>
  <% end %>
</div>